/* Mock fallback used when ANTHROPIC_API_KEY or FIRECRAWL_API_KEY are missing.
   Lets the UI work end-to-end during development without keys. */

import type { GenerateResponse, ResultNiche } from "@/lib/types";

export const MOCK_NICHES: ResultNiche[] = [
  {
    id: "boho-wedding-stationery",
    rank: 1,
    name: "Boho Wedding Stationery",
    taxonomy: ["Paper & Party Supplies", "Stationery", "Invitations"],
    inventory_model: "digital",
    score: 87,
    sub_scores: {
      demand: 21,
      competition: 14,
      margin: 18,
      ltv: 6,
      seasonality: 8,
      ad_recovery: 8,
      policy_penalty: 0,
      whitespace_bonus: 12,
    },
    confidence: "high",
    missing_signals: [],
    why: "Because you've got 5–15 hours a week and you're comfortable in Canva, this is digital-only, design once, sell forever. The modern minimalist + boho overlap maps to a sub-niche where Etsy currently has 12,400 listings (mid-density), and Pinterest's \"boho wedding invitation\" pin volume grew 38% over the last 12 months. Top sellers carry 200+ reviews and listings averaging $24, which is comfortably inside your side-income target.",
    startup_cost: "$80–150 (Canva Pro + initial listings)",
    time_to_first_sale: "2–4 weeks with consistent uploads",
    product_ideas: [
      "Editable boho save-the-date templates",
      "Modular invitation suites with 4 fonts",
      "Boho-meets-minimalist table number printables",
      "Welcome sign mockups (printable + Canva editable)",
      "Bridesmaid proposal cards in 3 color palettes",
    ],
    firecrawl: {
      total_listings: "12,400",
      top_10_avg_reviews: 213,
      top_10_avg_age_months: 18,
      top_10_avg_price: "$24",
      related_searches: [
        "boho invitation template",
        "minimalist wedding suite",
        "earthy wedding invitation",
        "neutral wedding stationery",
        "save the date editable",
        "arch wedding invitation",
      ],
    },
    hero_img: "https://images.unsplash.com/photo-1519741497674-611481863552?w=1200&q=80&auto=format&fit=crop",
    tags: ["Digital", "Wedding", "Boho", "Minimalist"],
    cf_query: "boho wedding invitation template",
  },
  {
    id: "minimalist-printable-wall-art",
    rank: 2,
    name: "Minimalist Printable Wall Art",
    taxonomy: ["Art & Collectibles", "Prints", "Digital Prints"],
    inventory_model: "digital",
    score: 78,
    sub_scores: {
      demand: 19,
      competition: 10,
      margin: 19,
      ltv: 5,
      seasonality: 7,
      ad_recovery: 7,
      policy_penalty: 0,
      whitespace_bonus: 11,
    },
    confidence: "high",
    missing_signals: [],
    why: "Your minimalist aesthetic and Canva skill align here cleanly, buyers want simple line drawings, neutral palettes, and gallery-wall sets. With 38,000 active listings the category is denser than wedding, but top sellers concentrate at the bundled-set level (e.g. \"set of 6 boho prints\") where you can differentiate.",
    startup_cost: "$80–150 (Canva Pro + mockup tool)",
    time_to_first_sale: "3–6 weeks",
    product_ideas: [
      "Set of 6 boho line-art prints (neutral palette)",
      "Botanical pressed-flower gallery wall set",
      "Minimalist affirmation prints",
      "Earth-tone abstract shapes trio",
      "Editable art with custom color picker",
    ],
    firecrawl: {
      total_listings: "38,100",
      top_10_avg_reviews: 412,
      top_10_avg_age_months: 26,
      top_10_avg_price: "$11",
      related_searches: [
        "boho wall art",
        "neutral printable",
        "line art print set",
        "minimalist art bundle",
        "gallery wall set",
      ],
    },
    hero_img: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=1200&q=80&auto=format&fit=crop",
    tags: ["Digital", "Wall Art", "Minimalist"],
    cf_query: "minimalist wall art printable",
  },
  {
    id: "boho-baby-milestone-cards",
    rank: 3,
    name: "Boho Baby Milestone Cards",
    taxonomy: ["Paper & Party Supplies", "Cards", "Milestone"],
    inventory_model: "digital",
    score: 71,
    sub_scores: {
      demand: 17,
      competition: 13,
      margin: 17,
      ltv: 6,
      seasonality: 6,
      ad_recovery: 7,
      policy_penalty: -2,
      whitespace_bonus: 7,
    },
    confidence: "medium",
    missing_signals: ["pinterest pin volume"],
    why: "This is the long-tail option, smaller volume, but your boho aesthetic reads strongly here and competition concentrates in literal nursery animal prints rather than the editorial direction you'd take. With ~8,200 listings and top sellers showing modest review counts, there's room for a clearer brand voice.",
    startup_cost: "$80–120",
    time_to_first_sale: "4–8 weeks",
    product_ideas: [
      "Earthy monthly milestone card set (1–12 months)",
      "Pregnancy weekly milestone cards",
      "Editable name + birth-stat cards",
      "Boho \"firsts\" memory card set",
      "Sibling announcement cards",
    ],
    firecrawl: {
      total_listings: "8,200",
      top_10_avg_reviews: 96,
      top_10_avg_age_months: 14,
      top_10_avg_price: "$9",
      related_searches: [
        "boho milestone cards",
        "neutral baby cards",
        "monthly milestone printable",
        "earthy nursery",
      ],
    },
    hero_img: "https://images.unsplash.com/photo-1522771930-78848d9293e8?w=1200&q=80&auto=format&fit=crop",
    tags: ["Digital", "Baby", "Boho"],
    cf_query: "baby milestone card template",
  },
];

export const MOCK_RESPONSE: GenerateResponse = {
  niches: MOCK_NICHES,
  source: "mock",
  warning: "Running with mock data, set ANTHROPIC_API_KEY and FIRECRAWL_API_KEY in .env.local for live recommendations.",
};
